# Database settings.
#database:

    # the name of your JDBC driver
    #driverClass: com.mysql.jdbc.Driver

    # the username
    #user: root

    # the password
    #password: Tiger@1234

#     the JDBC URL
#    url: jdbc:mysql://localhost:3306/atharvaDB

# Enable HTTPS
server:
  applicationConnectors:
  - type: http
    port: 9090
  adminConnectors:
  - type: http
    port: 9091


#TradeSettings
#tradeSettings:
stopLossStrategy: 2
timeInterval: 15000
riskOnCapital: 0.025
trendReversalStrategy: 1.0
trendReversalCriteria: 3
