# Database settings.
#database:

    # the name of your JDBC driver
    #driverClass: com.mysql.jdbc.Driver

    # the username
    #user: root

    # the password
    #password: Tiger@1234

#     the JDBC URL
#    url: jdbc:mysql://localhost:3306/atharvaDB

# Enable HTTPS
server:
  applicationConnectors:
  - type: http
    port: 9090
  adminConnectors:
  - type: http
    port: 9091


#TradeSettings
tradeSettings:
  stopLossStrategy: 3
  timeInterval: 15000
  riskOnCapital: 0.025
  trendFlagAvgStrategy: 1.0
  trendReversalCriteria: 3
  movingAvgSmallPeriod: 20
  movingAvgLargePeriod: 40
  movingAvgInterval: 60000
  movingAvgCrossOverDifferenceForStoploss: 0.00005
  movingAvgCrossOverDifferenceForReversal: 0.0001
  trendReversalCriteria: 3
  brokerage: 0.0005
